### ISSUE TITLE
Any idea on inference with TFJS?

### ISSUE THREAD

**Issue by navendu-pottekkat** [Rishit-dagli/MIRNet-TFJS#2]
The code looks good and the converted models look good too. But, how do we perform inference with TFJS? Seems like you have performed inference, not on the TFJS models and it uses a function from mirnet. So I am guessing we have to implement something similar for TFJS. 

If anyone has any idea or implementation for that it would be really helpful!

@Rishit-dagli Great work!

**Comment by navendu-pottekkat** [comment]
NVM I think it does not do much, just reshape the image and convert it into array.

I should have checked the code before!

**Comment by Rishit-dagli** [comment]
Thank You! I had that in the pipeline and planned to get out an example after the model is published on TF Hub. However, it makes a lot of sense to release a live demo and I have started working on that.

Thanks a lot for the suggestion.

**Comment by Rishit-dagli** [comment]
Hey @navendu-pottekkat , the implementation part have now been pushed an the details about the same have also been updates in the README. Let me know if you have any more questions.

**Comment by navendu-pottekkat** [comment]
@Rishit-dagli Great! I will take a look
